Proposed new function for messy - duplicate rows of data
nrennie/messy pull request #8
Opened 2024-11-19 11:42 UTC by Philip-Leftwich

This function, duplicate_rows, takes a dataframe and allows you to duplicate a certain percentage of its rows and reinsert them into the dataframe, either maintaining the original order or inserting them randomly.

Really cool package by the way - that I have already started using to add some mess to my students data!

2024-11-26 13:54 UTC, nrennie commented on R/duplicate_rows.R
> +#' @importFrom dplyr slice_sample mutate arrange
Please use namespacing not ImportFrom, then delete this line.

2024-11-26 13:54 UTC, nrennie commented on R/duplicate_rows.R
> +#' duplicate_rows_random_insert(mtcars, messiness = 0.1)
This example doesn't match the function name.

2024-11-26 13:59 UTC, nrennie commented
@Philip-Leftwich Thanks so much for this PR - it's definitely another messy data problem that students would benefit from practicing with! Just a couple of small fixes needed:

- Can you put the PR into `dev` rather than `main`?
- Can you update the NEWS file and bump the version number in the DESCRIPTION to 0.0.2.9000?
- Run `devtools::document()` to write the .Rd files for the new function

2024-11-26 14:01 UTC, nrennie requested changes
@Philip-Leftwich Thanks so much for this PR - it's definitely another messy data problem that students would benefit from practicing with! Just a couple of small fixes needed:

- Can you put the PR into dev rather than main?
- Can you update the NEWS file and bump the version number in the DESCRIPTION to 0.0.2.9000?
- Run `devtools::document()` to write the .Rd files for the new function
- Pass the linting checks with no warnings

2024-11-26 14:01 UTC, nrennie commented on R/duplicate_rows.R
> +    dplyr::mutate(original_index = row_number()) |>
add dplyr::

2024-12-01 14:16 UTC, merged

2024-12-03 10:01 UTC, Philip-Leftwich commented
Hi,
Thanks for doing those changes - I was off sick last week. Was just going to take a look now!